name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Install package
      run: |
        sudo apt-get -y install btrfs-progs-dev gpgme-dev device-mapper-dev

    - name: Test
      run: make test
